# Generated by Django 4.2.3 on 2023-08-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
