# Generated by Django 4.2.3 on 2023-09-01 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_todomodel_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
