# Generated by Django 4.2.3 on 2023-09-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_todomodel_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='finished_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
