# Generated by Django 4.2.3 on 2023-09-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_todomodel_finished_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='finished_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
