# Generated by Django 4.2.3 on 2023-09-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_alter_todomodel_finished_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='level',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1),
        ),
    ]
